# Generated by Django 4.0.6 on 2022-07-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
