# Generated by Django 4.0.6 on 2022-08-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
    ]
