# Generated by Django 4.0.6 on 2022-08-16 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
